// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropiedadesMinimalApi.Data;

#nullable disable

namespace PropiedadesMinimalApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241202223138_Creacion_Inicial_")]
    partial class Creacion_Inicial_
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropiedadesMinimalApi.Models.Propiedad", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropiedad");

                    b.ToTable("Propiedad");

                    b.HasData(
                        new
                        {
                            IdPropiedad = 1,
                            Activa = true,
                            Descripcion = "Amplia casa, recien remodelada, de dos planta",
                            FechaCreacion = new DateTime(2024, 11, 25, 16, 31, 37, 674, DateTimeKind.Local).AddTicks(7331),
                            Nombre = "Casa en la torres",
                            Ubicacion = "Guadalajara"
                        },
                        new
                        {
                            IdPropiedad = 2,
                            Activa = true,
                            Descripcion = "Torre de departamentos",
                            FechaCreacion = new DateTime(2024, 11, 24, 16, 31, 37, 677, DateTimeKind.Local).AddTicks(6050),
                            Nombre = "Departamentos Bimbo",
                            Ubicacion = "Tonala"
                        },
                        new
                        {
                            IdPropiedad = 3,
                            Activa = true,
                            Descripcion = "Terreno baldio en zona con alta plusvalia",
                            FechaCreacion = new DateTime(2024, 11, 25, 16, 31, 37, 677, DateTimeKind.Local).AddTicks(6074),
                            Nombre = "Terreno baldio uno",
                            Ubicacion = "Zapopan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
